# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5
PYTHON_COMPAT=( python{2_6,2_7} pypy2_0 )

inherit distutils-r1 flag-o-matic

DESCRIPTION="A pypy capable Pythonic binding for the libxml2 and libxslt libraries"
HOMEPAGE="http://lxml.de/ http://pypi.python.org/pypi/lxml/"
SRC_URI="http://dev.gentoo.org/~idella4/tarballs/${P}.tar.gz"

LICENSE="BSD ElementTree GPL-2 PSF-2"
SLOT="0"
KEYWORDS="~alpha ~amd64 ~arm ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86 ~amd64-fbsd ~x86-fbsd ~amd64-linux ~x86-linux ~ppc-macos ~x86-macos ~sparc-solaris ~x64-solaris ~x86-solaris"
IUSE="doc examples test +threads"

# Note: lib{xml2,xslt} are used as C libraries, not Python modules.
RDEPEND=">=dev-libs/libxml2-2.7.2
	>=dev-libs/libxslt-1.1.15

	dev-python/beautifulsoup[${PYTHON_USEDEP}]"
DEPEND="${RDEPEND}
	dev-python/setuptools[${PYTHON_USEDEP}]
	test? ( !dev-python/elementtree )"
#DISTUTILS_IN_SOURCE_BUILD=1

# lxml tarball contains files pregenerated by Cython.

python_prepare_all() {
	# avoid replacing PYTHONPATH in tests.
	sed -i -e '/sys\.path/d' test.py || die

	distutils-r1_python_prepare_all
}

python_compile() {
#	if [[ ${EPYTHON} != python3* ]]; then
#		local CFLAGS=${CFLAGS}
#		append-cflags -fno-strict-aliasing
#	fi
#	esetup.py build_ext -i --without_cython
	:
}

python_test() {
#	cp -r -l src/lxml/tests build/temp.linux*/lxml/ || die
#	cp -r -l src/lxml/html/tests build/temp.linux*/lxml/html/ || die
#	ln -s "${S}"/doc build/ || die

	local test
	if [[ "${EPYTHON}" == 'python3.1' ]]; then
		einfo "Many tests not compatible to py3.1"
		return 0
	else
		for test in test.py selftest.py selftest2.py; do
			einfo "Running ${test}"
			PYTHONPATH=src/ "${PYTHON}" ${test} || die "Test ${test} fails with ${EPYTHON}"
		done
	fi
}

python_install_all() {
	if use doc; then
		local DOCS=( *.txt doc/*.txt )
		local HTML_DOCS=( doc/html/. )
	fi

	distutils-r1_python_install_all

	if use examples; then
		docinto examples
		dodoc -r samples/*
		docompress -x /usr/share/doc/${PF}/examples
	fi
}
